Repository kimyoo04/signlanguage-project, pull requests merged in 2023-05, with the labels that each got.

#2 feat: frontend 깃 무시 추가
  frontend/.gitignore
Labels: documentation

#4 Ai feature/google bard 함수 생성
  mini7/chatgpt/views.py
  mini7/question/bard.py
  mini7/selfchatgpt/views.py
Labels: AI

#5 docs: requirements.txt bardapi 추가
  mini7/requirements.txt
Labels: AI

#6 feat: add signLanguage translate
  mini7/.gitignore
  mini7/mysite/settings.py
  mini7/mysite/urls.py
  mini7/selfsignlanguagetochatgpt/__pycache__/desktop.ini
  mini7/selfsignlanguagetochatgpt/apps.py
  mini7/selfsignlanguagetochatgpt/desktop.ini
  mini7/selfsignlanguagetochatgpt/migrations/0001_initial.py
  mini7/selfsignlanguagetochatgpt/migrations/__pycache__/desktop.ini
  mini7/selfsignlanguagetochatgpt/migrations/desktop.ini
  mini7/selfsignlanguagetochatgpt/models.py
  mini7/selfsignlanguagetochatgpt/static/desktop.ini
  mini7/selfsignlanguagetochatgpt/static/languagechat/chat_style.css
  mini7/selfsignlanguagetochatgpt/static/languagechat/desktop.ini
  mini7/selfsignlanguagetochatgpt/static/languagechat/style.css
  mini7/selfsignlanguagetochatgpt/templates/desktop.ini
  mini7/selfsignlanguagetochatgpt/templates/languagechat/desktop.ini
  mini7/selfsignlanguagetochatgpt/templates/languagechat/index.html
  mini7/selfsignlanguagetochatgpt/templates/languagechat/result.html
  mini7/selfsignlanguagetochatgpt/templates/selflanguagechat/index.html
  mini7/selfsignlanguagetochatgpt/templates/selflanguagechat/result.html
  mini7/selfsignlanguagetochatgpt/tests.py
  mini7/selfsignlanguagetochatgpt/urls.py
  mini7/selfsignlanguagetochatgpt/views.py
Labels: BE

#7 BE-feature: post Create, Read, Read_posts_list 생성
  mini7/posts/__init__.py
  mini7/posts/apps.py
  mini7/posts/forms.py
  mini7/posts/migrations/0001_initial.py
  mini7/posts/migrations/__init__.py
  mini7/posts/models.py
  mini7/posts/urls.py
  mini7/posts/views.py
Labels: BE

#9 fix: 게시판 조회 json 형식 수정, 게시글 조회수 증가 기능 추가, 수정 기능 추가, 게시글 삭제 기능 추가
  mini7/posts/views.py
Labels: BE

#10 feat: bard chatgpt 병합
  mini7/question/bard.py
Labels: AI

#12 fix: bard.py를 bard_gpt.py로 파일명 수정
  mini7/question/bard_gpt.py
Labels: AI

#11 feat: 회원가입 기능 추가
  mini7/mysite/urls.py
  mini7/signup/__init__.py
  mini7/signup/admin.py
  mini7/signup/apps.py
  mini7/signup/migrations/__init__.py
  mini7/signup/models.py
  mini7/signup/tests.py
  mini7/signup/urls.py
  mini7/signup/views.py
Labels: BE

#13 fix: url 충돌 문제 수정
  mini7/account/__init__.py
  mini7/account/admin.py
  mini7/account/apps.py
  mini7/account/migrations/__init__.py
  mini7/account/models.py
  mini7/account/tests.py
  mini7/account/urls.py
  mini7/account/views.py
  mini7/mysite/settings.py
  mini7/mysite/urls.py
Labels: bug, BE

#14 Fe feature/홈페이지 UI 업데이트
  docker-compose.yml
  frontend/public/images/bardai.png
  frontend/public/images/chatbot2.png
  frontend/public/images/chatgpt_api.png
  frontend/public/images/folders.png
  frontend/public/images/mlflow.png
  frontend/public/images/수어번역서비스 모델 설명.png
  frontend/src/scenes/Home/ChatGPTIntro/index.tsx
  frontend/src/scenes/Home/Hero/index.tsx
  frontend/src/scenes/Home/Introduce/index.tsx
  frontend/src/scenes/Home/SignLanguageIntro/index.tsx
  frontend/src/scenes/Home/Team/index.tsx
  frontend/src/scenes/SignLanguage/index.tsx
Labels: FE

#15 feat: 회원가입에 로그인, 로그아웃 추가
  mini7/account/urls.py
  mini7/account/views.py
  mini7/mysite/settings.py
Labels: BE

#18 fix: api/chat/ 링크에 bard_gpt 연결
  mini7/mysite/settings.py
  mini7/posts/__pycache__/__init__.cpython-39.pyc
  mini7/posts/__pycache__/admin.cpython-39.pyc
  mini7/posts/__pycache__/apps.cpython-39.pyc
  mini7/posts/__pycache__/forms.cpython-39.pyc
  mini7/posts/__pycache__/models.cpython-39.pyc
  mini7/posts/__pycache__/urls.cpython-39.pyc
  mini7/posts/__pycache__/views.cpython-39.pyc
  mini7/posts/migrations/__pycache__/0001_initial.cpython-39.pyc
  mini7/posts/migrations/__pycache__/__init__.cpython-39.pyc
  mini7/selfchatgpt/urls.py
  mini7/selfchatgpt/views.py
  mini7/selfsignlanguagetochatgpt/__pycache__/__init__.cpython-39.pyc
  mini7/selfsignlanguagetochatgpt/__pycache__/apps.cpython-39.pyc
Labels: BE

#19 feat: 로그인 기능 쿠키에 jwt 토큰 추가
  mini7/account/views.py
Labels: BE

#21 fix: create_post 작성자 수정
  mini7/posts/views.py
Labels: BE

#22 feat: readme 파일 작성
  README.md
Labels: documentation

#23 fix: bard_gpt 문자열 랜덤 반환하게 수정
  mini7/selfchatgpt/views.py
  mini7/selfsignlanguagetochatgpt/views.py
Labels: BE

#25 Be feature/url 슬래시 제거
  mini7/account/urls.py
  mini7/mysite/settings.py
  mini7/mysite/urls.py
  mini7/posts/urls.py
  mini7/requirements.txt
Labels: BE

#26 Fe feature/프록시 설정 및 image loader 설정
  docker-compose.yml
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/posts/new/index.tsx
  frontend/src/api/auth/logout.ts
  frontend/src/api/auth/signin.ts
  frontend/src/api/auth/signup.ts
  frontend/src/api/axiosInstance.ts
  frontend/src/api/chat/sendQuestion.ts
  frontend/src/api/posts/createPost.ts
  frontend/src/api/posts/deletePost.ts
  frontend/src/api/posts/readPost.ts
  frontend/src/api/posts/readPostDetail.ts
  frontend/src/api/posts/readPosts.ts
  frontend/src/api/posts/updatePost.ts
  frontend/src/api/signLanguage/signLanguage.ts
  frontend/src/scenes/Posts/AddPost/index.tsx
  frontend/src/scenes/Posts/EditPost/index.tsx
  frontend/src/scenes/Posts/postDetail/index.tsx
  frontend/src/scenes/SignLanguage/index.tsx
  frontend/src/scenes/Signin/index.tsx
  frontend/src/scenes/Signup/index.tsx
  frontend/src/type/posts.ts
  frontend/src/util/localImageLoader.ts
  frontend/styles/globals.css
Labels: FE

#27 Fe feature/수화번역 구현
  frontend/pages/signLanguage/index.tsx
  frontend/src/scenes/SignLanguage/index.tsx
Labels: FE

#28 docs: README 수정
  README.md
Labels: documentation
